# Generated by Django 4.0.2 on 2022-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smartphones',
            new_name='Electronics',
        ),
    ]
