# Generated by Django 4.0.2 on 2022-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_electronics_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
