# Generated by Django 4.0.2 on 2022-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0007_alter_operatingsystem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronics',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Smartphone'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['name'], 'verbose_name': 'Sistema operativo', 'verbose_name_plural': 'Sistemi operativi'},
        ),
        migrations.AlterField(
            model_name='electronics',
            name='content',
            field=models.TextField(unique=True, verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificato'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Brand'),
        ),
    ]
