# Generated by Django 4.0.2 on 2022-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_rename_smartphones_electronics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='title',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
