# Generated by Django 4.0.2 on 2022-02-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_category_alter_electronics_content_electronics_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='OperatingSystem',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='cat',
            new_name='opsys',
        ),
    ]
